
music_directory     "~/Music"
playlist_directory  "~/.config/mpd/playlists"
db_file             "~/.config/mpd/database"
log_file            "~/.config/mpd/log"
pid_file            "~/.config/mpd/pid"
state_file          "~/.config/mpd/state"
sticker_file        "~/.config/mpd/sticker.sql"

bind_to_address     "127.0.0.1"
port                "6600"
audio_buffer_size "8192"
buffer_before_play "10%"


#audio_output {
#    type            "pulse"
#    name            "PipeWire"
#    mixer_type      "software"
#}

audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
        mixer_type      "hardware"
}

