# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict
# if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables
# See also Laptops.conf for laptops keybinds

# /* ---- ✴️ Variables ✴️ ---- */  #
$mainMod = SUPER
$files = nautilus
$term = kitty
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

#  IMPORTANT: If you want to remap and existing keybind you MUST unbindd it first

# The bindings are CASE SENSITIVE. We suggest you copy the exisitng binding here
#  Then change `bindd` to `unbind`

# E.g.
# unbind = $mainMod, Return, Open terminal, exec, $term
# bindd = $mainMod, Return, Open terminal, exec, ghostty
#
# unbind = $mainMod, E, file manager, exec, $files
# bindd = $mainMod, T, file manager, exec, $files

# If you are ADDING a bindd, make sure you include the description
# Other the keybind search menu might not show it properly

# E.g.
# bindd = $mainMod, Z, My z app, exec APPNAME

# settings for User defaults apps - set your default terminal andv file manager on this file
source= $UserConfigs/01-UserDefaults.conf

# common shortcuts
#bindr = $mainMod, $mainMod_L, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window # Super Key to Launch rofi menu
bindd = $mainMod, Space, app launcher, exec, pkill rofi || true && rofi -show drun -modi drun,filebrowser,run,window
bindd = $mainMod, B, open default browser, exec, xdg-open "https://"
bindd = $mainMod, A, desktop overview, exec, $scriptsDir/OverviewToggle.sh # toggles quickshell or ags overview (tries QS first, falls back to AGS)
#bindd = $mainMod, A, ags overview, exec, pkill rofi || true && ags -t 'overview' # desktop overview (if installed)
#bindd = $mainMod, A, Quickshell overview, global, quickshell:overviewToggle # desktop overview (if installed)
bindd = $mainMod, Return, Open terminal, exec, $term
bindd = $mainMod, E, file manager, exec, $files
bind = $mainMod, V, exec, $scriptsDir/nerd-dictation-toggle.sh



bindd = $mainMod ALT, F, fullscreen, fullscreen
bindd = $mainMod , F, maximize window, fullscreen, 1
bindd = $mainMod SHIFT, F, Float current window, togglefloating,
bindd = $mainMod CTRL, F, Float all windows, exec, hyprctl dispatch workspaceopt allfloat
#bindd = $mainMod SHIFT, Return, DropDown terminal, exec, [float; move 15% 5%; size 70% 60%] $term




# For passthrough keyboard into a VM
# bind = $mainMod ALT, P, submap, passthru
#submap = passthru
# to unbind
#bind = $mainMod ALT, P, submap, reset
#submap = reset

bind = $mainMod SHIFT, Return, exec, pypr toggle term # Dropdown terminal not avail Debian and Ubuntu
bind = $mainMod SHIFT, Slash, exec, pypr toggle ncmpcpp # Dropdown Music
bind = $mainMod, Z, exec, pypr zoom # Toggle Desktop Zoom
